// src/lib/embeddingCases.js
// Static content data for the Embedding Explorer ("The Word Vault") activity.
// Three cases of increasing difficulty exploring how word embeddings work.

export const PHASES = [
  { id: "briefing",    label: "Project Brief",    emoji: "\uD83D\uDCCB", num: 1 },
  { id: "dataroom",    label: "Word Lab",         emoji: "\uD83D\uDD2C", num: 2 },
  { id: "exploration", label: "Space Explorer",    emoji: "\uD83D\uDE80", num: 3 },
  { id: "evidence",    label: "Pattern Locker",    emoji: "\uD83D\uDD12", num: 4 },
  { id: "report",      label: "Engineer\u2019s Report", emoji: "\uD83D\uDCDD", num: 5 },
  { id: "review",      label: "Project Review",    emoji: "\u2B50", num: 6 },
];

export const DIFFICULTY_COLORS = {
  1: { label: "Beginner",     color: "var(--cyan, #22d3ee)" },
  2: { label: "Intermediate", color: "var(--purple, #b08eff)" },
  3: { label: "Advanced",     color: "var(--amber, #f5a623)" },
};

export const CASES = [
  // ════════════════════════════════════════════════════════════════
  // CASE 1: "The Number Problem"
  // ════════════════════════════════════════════════════════════════
  {
    id: "number-problem",
    title: "The Number Problem",
    subtitle: "Why Words Need Vectors",
    description: "LexiCorp's original Word Vault used a single number per word \u2014 and it's a disaster. Similar words get wildly different numbers, synonyms are scattered, and the system can't tell 'happy' from 'hammer'. Your mission: figure out why one number isn't enough, and discover how multi-dimensional representations actually capture meaning.",
    emoji: "\uD83D\uDD22",
    difficulty: 1,
    difficultyLabel: "Beginner",
    totalInsights: 6,
    estimatedTime: "25\u201335 min",
    color: "var(--cyan, #22d3ee)",

    aiSystem: {
      name: "Word Vault v1.0",
      purpose: "Convert words to numerical IDs for storage and search",
      deployer: "LexiCorp",
      launchedYear: 2019,
      vocabularySize: "50,000 words",
    },

    labSections: [
      {
        key: "single-number",
        title: "The Single-Number System",
        subtitle: "Why one number per word fails",
        content: "LexiCorp's original system assigned each word a single number based on alphabetical order. Here's the problem:",
        data: [
          { word: "happy", value: 12847, group: "emotion" },
          { word: "joyful", value: 15923, group: "emotion" },
          { word: "sad", value: 34201, group: "emotion" },
          { word: "hammer", value: 12901, group: "tool" },
          { word: "wrench", value: 48322, group: "tool" },
          { word: "king", value: 16402, group: "royalty" },
          { word: "queen", value: 30119, group: "royalty" },
          { word: "puppy", value: 29044, group: "animal" },
        ],
        vizType: "numberLine",
        question: {
          prompt: "In this single-number system, which word is closest to 'happy' (12847)?",
          choices: [
            { id: "a", text: "'joyful' (15923) \u2014 a synonym" },
            { id: "b", text: "'hammer' (12901) \u2014 a tool" },
            { id: "c", text: "'sad' (34201) \u2014 an antonym" },
            { id: "d", text: "'king' (16402) \u2014 royalty" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Exactly! 'Hammer' is numerically closest to 'happy' because they're near each other alphabetically \u2014 but they have nothing to do with each other. This is why a single number can't capture meaning.",
          feedbackIncorrect: "Look at the numbers: 'happy' is 12847, and 'hammer' is 12901 \u2014 only 54 apart! Alphabetical ordering puts unrelated words close together.",
        },
      },
      {
        key: "two-dimensions",
        title: "Adding a Second Dimension",
        subtitle: "How 2 numbers improve word relationships",
        content: "What if we use TWO numbers per word? Now we can place words on a 2D plane where position encodes meaning:",
        data: [
          { word: "happy",   x: 0.8,  y: 0.9,  group: "emotion" },
          { word: "joyful",  x: 0.85, y: 0.88, group: "emotion" },
          { word: "sad",     x: 0.75, y: 0.1,  group: "emotion" },
          { word: "angry",   x: 0.9,  y: 0.15, group: "emotion" },
          { word: "hammer",  x: 0.1,  y: 0.5,  group: "tool" },
          { word: "wrench",  x: 0.15, y: 0.55, group: "tool" },
          { word: "king",    x: 0.5,  y: 0.85, group: "royalty" },
          { word: "queen",   x: 0.55, y: 0.9,  group: "royalty" },
        ],
        vizType: "scatter2D",
        question: {
          prompt: "In the 2D system, which word is now closest to 'happy' (0.8, 0.9)?",
          choices: [
            { id: "a", text: "'joyful' (0.85, 0.88) \u2014 a synonym" },
            { id: "b", text: "'hammer' (0.1, 0.5) \u2014 a tool" },
            { id: "c", text: "'king' (0.5, 0.85) \u2014 royalty" },
            { id: "d", text: "'sad' (0.75, 0.1) \u2014 an antonym" },
          ],
          correctAnswer: "a",
          feedbackCorrect: "Now 'joyful' is closest to 'happy' \u2014 exactly as we'd expect! Two dimensions let us separate meaning from alphabetical order.",
          feedbackIncorrect: "Calculate the distance: 'joyful' at (0.85, 0.88) is just 0.05 away from 'happy' at (0.8, 0.9). Two dimensions let synonyms cluster together.",
        },
      },
      {
        key: "many-dimensions",
        title: "The Power of 300 Dimensions",
        subtitle: "Why real embeddings use hundreds of numbers",
        content: "Two dimensions help, but language is far more complex. Real word embeddings use 300+ dimensions. Each dimension captures a different aspect of meaning: formality, emotion, concreteness, gender associations, and hundreds more.",
        data: [
          { label: "1 dimension",   dims: 1,   synonymAccuracy: 12, analogyAccuracy: 0,  clusterPurity: 8 },
          { label: "2 dimensions",  dims: 2,   synonymAccuracy: 45, analogyAccuracy: 10, clusterPurity: 35 },
          { label: "50 dimensions", dims: 50,  synonymAccuracy: 78, analogyAccuracy: 55, clusterPurity: 72 },
          { label: "300 dimensions", dims: 300, synonymAccuracy: 95, analogyAccuracy: 85, clusterPurity: 93 },
        ],
        vizType: "dimensionBars",
        question: {
          prompt: "What happens when you go from 50 to 300 dimensions?",
          choices: [
            { id: "a", text: "Only synonym accuracy improves significantly" },
            { id: "b", text: "All three metrics improve substantially" },
            { id: "c", text: "Diminishing returns \u2014 the improvement is tiny" },
            { id: "d", text: "Analogy accuracy actually decreases" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Right! Going from 50 to 300 dimensions boosts synonym accuracy from 78% to 95%, analogy accuracy from 55% to 85%, and cluster purity from 72% to 93%. More dimensions capture more nuances of meaning.",
          feedbackIncorrect: "Look at all three metrics: synonym accuracy jumps from 78% to 95%, analogy accuracy from 55% to 85%, and cluster purity from 72% to 93%. All improve substantially!",
        },
      },
      {
        key: "polysemy",
        title: "Words With Multiple Meanings",
        subtitle: "The polysemy challenge",
        content: "The word 'bank' can mean a financial institution OR a river bank. How should a single vector handle this? Early embeddings averaged all meanings together, creating a blurry representation that's not quite right for either meaning.",
        data: [
          { word: "bank",    meanings: ["financial institution", "river bank", "to bank on"], avgPosition: "between finance and nature clusters" },
          { word: "bat",     meanings: ["flying mammal", "baseball bat"], avgPosition: "between animal and sports clusters" },
          { word: "crane",   meanings: ["bird", "construction machine"], avgPosition: "between animal and machinery clusters" },
          { word: "spring",  meanings: ["season", "water source", "coil", "to jump"], avgPosition: "scattered across multiple clusters" },
        ],
        vizType: "polysemyCards",
        question: {
          prompt: "If 'bank' has one vector averaging its meanings, where does it end up?",
          choices: [
            { id: "a", text: "Perfectly centered in the finance cluster" },
            { id: "b", text: "Somewhere between finance and nature clusters \u2014 not ideal for either" },
            { id: "c", text: "In a special 'ambiguous words' region" },
            { id: "d", text: "It gets two separate vectors automatically" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Exactly! The averaged vector sits between the two meaning clusters, which means it's not a great match for either 'financial bank' or 'river bank'. This is a fundamental limitation of single-vector embeddings.",
          feedbackIncorrect: "When you average the financial and river-bank contexts, the resulting vector lands somewhere between the finance and nature clusters \u2014 not ideal for either meaning.",
        },
      },
    ],

    insights: [
      {
        id: "np-representation",
        title: "Representation Matters",
        category: "Foundation",
        description: "How you represent information determines what patterns a computer can find. Alphabetical ordering destroys meaning relationships that numerical proximity should encode.",
        evidence: "In the single-number system, 'happy' (12847) was closer to 'hammer' (12901) than to 'joyful' (15923) \u2014 the representation made similar words look different.",
        points: 8,
        question: {
          prompt: "Why does alphabetical ordering fail to capture word meaning?",
          choices: [
            { id: "a", text: "The alphabet is too short for all words" },
            { id: "b", text: "Alphabetical order is arbitrary \u2014 it has no relationship to meaning" },
            { id: "c", text: "Some letters are more meaningful than others" },
            { id: "d", text: "Computers can't process alphabetical data" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Right! Alphabetical order is a human convention for looking up words in dictionaries. It tells us nothing about what words mean \u2014 'happy' and 'hammer' start with 'ha' but have completely unrelated meanings.",
          feedbackWrong: {
            a: "The alphabet's length isn't the issue \u2014 it's that alphabetical order has nothing to do with meaning.",
            c: "No letters are inherently more 'meaningful' \u2014 the issue is that alphabetical order doesn't encode meaning at all.",
            d: "Computers can absolutely process alphabetical data. The problem is that alphabetical proximity doesn't equal semantic proximity.",
          },
        },
      },
      {
        id: "np-dimensions",
        title: "Dimensionality = Expressiveness",
        category: "Foundation",
        description: "More dimensions allow a system to capture more nuances of meaning simultaneously. Each dimension can represent a different aspect: formality, emotion, concreteness, etc.",
        evidence: "Synonym accuracy jumped from 12% (1D) to 45% (2D) to 95% (300D). Analogy accuracy went from 0% to 85%. More dimensions = more aspects of meaning captured.",
        points: 7,
        question: {
          prompt: "Why do more dimensions help capture word meaning?",
          choices: [
            { id: "a", text: "More numbers mean more storage space, which improves accuracy" },
            { id: "b", text: "Each dimension can encode a different aspect of meaning (emotion, formality, etc.)" },
            { id: "c", text: "Higher dimensions make the math easier to compute" },
            { id: "d", text: "300 is a magic number that perfectly represents all languages" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Exactly! Think of each dimension as a slider for a different aspect of meaning: one might capture how emotional a word is, another how concrete vs. abstract, another how formal. More sliders = more nuance.",
          feedbackWrong: {
            a: "Storage space isn't the benefit \u2014 it's the ability to encode multiple aspects of meaning simultaneously.",
            c: "Higher dimensions actually make computation more expensive. The benefit is richer representation.",
            d: "300 isn't magic \u2014 it's just a practical balance. The key insight is that EACH dimension adds expressive capacity.",
          },
        },
      },
      {
        id: "np-context",
        title: "Context Shapes Meaning",
        category: "Language",
        description: "Words derive meaning from the company they keep. Embeddings learn from context: words that appear in similar contexts get similar vectors, even if they never appear together.",
        evidence: "'Happy' and 'joyful' rarely appear in the exact same sentence, but they both appear near words like 'smile', 'celebrate', 'wonderful' \u2014 so their embeddings cluster together.",
        points: 6,
        question: {
          prompt: "How do embedding models learn that 'happy' and 'joyful' are similar?",
          choices: [
            { id: "a", text: "A human labels them as synonyms in a dictionary" },
            { id: "b", text: "They appear in similar surrounding contexts in training data" },
            { id: "c", text: "They have similar letter patterns" },
            { id: "d", text: "The model randomly assigns them nearby positions" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Right! This is the distributional hypothesis: 'You shall know a word by the company it keeps.' Both words appear near 'smile', 'celebrate', 'excited' \u2014 so the model learns they must be related.",
          feedbackWrong: {
            a: "Embeddings are trained on raw text, not dictionary labels. The model discovers relationships automatically from patterns.",
            c: "Letter patterns are irrelevant \u2014 'happy' and 'joyful' look nothing alike. Meaning comes from context.",
            d: "There's nothing random about it. The positions are learned from millions of text examples.",
          },
        },
      },
      {
        id: "np-polysemy",
        title: "The Polysemy Problem",
        category: "Limitation",
        description: "Words with multiple meanings (polysemy) challenge single-vector embeddings. The vector becomes a blurry average of all meanings, poorly representing each individual sense.",
        evidence: "'Bank' (finance vs. river) gets a single vector that sits between the finance and nature clusters \u2014 it's a mediocre match for either meaning.",
        points: 7,
        question: {
          prompt: "What's the main problem with giving polysemous words a single vector?",
          choices: [
            { id: "a", text: "It uses too much memory" },
            { id: "b", text: "The averaged vector doesn't accurately represent any individual meaning" },
            { id: "c", text: "Computers can't understand words with multiple meanings" },
            { id: "d", text: "It makes the training process take longer" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Exactly! Averaging 'financial institution' and 'river bank' creates a vector that's a mediocre match for either. It's like describing someone as 'average height' when they're actually two different people.",
          feedbackWrong: {
            a: "Memory isn't the issue \u2014 one vector actually uses less memory. The problem is representation quality.",
            c: "Modern contextual models (like BERT) actually handle polysemy well. The issue is with STATIC single-vector approaches.",
            d: "Training time isn't the core issue. The problem is that one vector can't faithfully represent multiple distinct meanings.",
          },
        },
      },
      {
        id: "np-not-human",
        title: "Not How Humans Think",
        category: "Meta",
        description: "Embeddings capture statistical patterns, not true understanding. A model can learn that 'doctor' and 'nurse' are similar without knowing what healthcare is.",
        evidence: "Embeddings can identify that 'Paris' relates to 'France' like 'Tokyo' relates to 'Japan' purely from word co-occurrence patterns \u2014 no geography knowledge required.",
        points: 6,
        question: {
          prompt: "What do word embeddings actually capture?",
          choices: [
            { id: "a", text: "The true definitions and meanings of words" },
            { id: "b", text: "Statistical patterns of which words appear in similar contexts" },
            { id: "c", text: "The emotional impact of each word" },
            { id: "d", text: "Only the grammatical category (noun, verb, adjective)" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Right! Embeddings are pattern detectors, not meaning understanders. They capture that 'doctor' and 'nurse' co-occur with 'hospital', 'patient', 'care' \u2014 but they don't 'know' what healthcare is.",
          feedbackWrong: {
            a: "Embeddings approximate meaning through statistics, but they don't truly 'understand' definitions the way humans do.",
            c: "Emotion is ONE aspect that might be partially captured, but embeddings encode many dimensions of statistical relationships.",
            d: "Embeddings capture much more than grammar \u2014 they encode semantic relationships, topic clusters, and analogy structures.",
          },
        },
      },
      {
        id: "np-tradeoffs",
        title: "The Dimension Tradeoff",
        category: "Engineering",
        description: "More dimensions improve accuracy but increase computation and storage costs. Engineers must balance expressiveness against practical constraints like speed and memory.",
        evidence: "Going from 50 to 300 dimensions improved accuracy by ~20 percentage points but increased storage by 6x and computation time by ~4x. Engineers chose 300 as a practical sweet spot.",
        points: 6,
        question: {
          prompt: "Why don't engineers just use 10,000 dimensions for perfect accuracy?",
          choices: [
            { id: "a", text: "10,000 dimensions would actually decrease accuracy" },
            { id: "b", text: "The practical costs (speed, memory, storage) outweigh the marginal accuracy gains" },
            { id: "c", text: "No computer is powerful enough" },
            { id: "d", text: "There are only 300 aspects of meaning in any language" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Exactly! After a certain point, adding more dimensions gives diminishing returns in accuracy while linearly increasing costs. 300 dimensions is a sweet spot \u2014 good accuracy at manageable cost.",
          feedbackWrong: {
            a: "Very high dimensions can cause 'overfitting' in some cases, but the main concern is practical cost, not decreased accuracy.",
            c: "Modern computers can handle millions of dimensions. The issue is efficiency: 300D is accurate enough while being much faster.",
            d: "Language has infinite nuances. 300 is a practical compromise, not a natural limit of meaning.",
          },
        },
      },
    ],

    findingsToIdentify: [
      { id: "f-single-fails", name: "Single-number representations fail to capture meaning" },
      { id: "f-multi-dim", name: "Multiple dimensions encode multiple aspects of meaning" },
      { id: "f-context-learned", name: "Embeddings learn meaning from context patterns" },
      { id: "f-polysemy-limit", name: "Polysemous words challenge single-vector models" },
      { id: "f-stats-not-meaning", name: "Embeddings capture statistics, not true understanding" },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // CASE 2: "The Similarity Engine"
  // ════════════════════════════════════════════════════════════════
  {
    id: "similarity-engine",
    title: "The Similarity Engine",
    subtitle: "Proximity, Analogies & Applications",
    description: "LexiCorp wants to ship the Word Vault to power search, recommendations, and translation. But first, you need to prove it actually works. Your mission: demonstrate that proximity equals similarity, explore how vector arithmetic enables analogies, and propose three real-world applications.",
    emoji: "\uD83E\uDDE2",
    difficulty: 2,
    difficultyLabel: "Intermediate",
    totalInsights: 6,
    estimatedTime: "30\u201340 min",
    color: "var(--purple, #b08eff)",

    aiSystem: {
      name: "Word Vault v2.0 \u2014 Similarity Engine",
      purpose: "Power search, recommendations, and translation using word proximity",
      deployer: "LexiCorp",
      launchedYear: 2021,
      vocabularySize: "400,000 words",
    },

    labSections: [
      {
        key: "clusters",
        title: "Semantic Clusters",
        subtitle: "Words naturally group by meaning",
        content: "When we plot words in embedding space, remarkable patterns emerge. Words cluster by topic, and related clusters sit near each other:",
        data: [
          { word: "dog",      x: 0.2,  y: 0.7,  group: "animals" },
          { word: "cat",      x: 0.25, y: 0.75, group: "animals" },
          { word: "puppy",    x: 0.18, y: 0.73, group: "animals" },
          { word: "kitten",   x: 0.27, y: 0.78, group: "animals" },
          { word: "car",      x: 0.8,  y: 0.3,  group: "vehicles" },
          { word: "truck",    x: 0.85, y: 0.25, group: "vehicles" },
          { word: "bus",      x: 0.78, y: 0.28, group: "vehicles" },
          { word: "bicycle",  x: 0.7,  y: 0.35, group: "vehicles" },
          { word: "doctor",   x: 0.5,  y: 0.85, group: "professions" },
          { word: "nurse",    x: 0.48, y: 0.82, group: "professions" },
          { word: "teacher",  x: 0.55, y: 0.8,  group: "professions" },
          { word: "lawyer",   x: 0.58, y: 0.78, group: "professions" },
          { word: "pizza",    x: 0.3,  y: 0.2,  group: "food" },
          { word: "pasta",    x: 0.35, y: 0.18, group: "food" },
          { word: "sushi",    x: 0.28, y: 0.15, group: "food" },
          { word: "burger",   x: 0.33, y: 0.22, group: "food" },
        ],
        vizType: "clusterScatter",
        question: {
          prompt: "What pattern do you observe about how words are arranged in embedding space?",
          choices: [
            { id: "a", text: "Words are randomly scattered with no visible pattern" },
            { id: "b", text: "Words cluster by meaning \u2014 similar words are physically close together" },
            { id: "c", text: "Words are arranged alphabetically" },
            { id: "d", text: "All words form a single large cluster" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Exactly! Animals cluster together, vehicles cluster together, food clusters together. This emergent organization happens automatically from training on text data \u2014 no one told the model to group them.",
          feedbackIncorrect: "Look at the plot carefully: dog/cat/puppy are all close together, car/truck/bus are close together. Words naturally group by semantic category!",
        },
      },
      {
        key: "analogies",
        title: "Vector Arithmetic = Analogies",
        subtitle: "king \u2212 man + woman = queen",
        content: "The most surprising property of word embeddings: you can do arithmetic with meaning! Subtracting and adding vectors creates analogies:",
        data: [
          {
            label: "king \u2212 man + woman = ?",
            equation: ["king", "\u2212", "man", "+", "woman", "=", "queen"],
            explanation: "The 'royalty' component of king minus the 'male' component plus the 'female' component = queen",
            result: "queen",
            topResults: [
              { word: "queen", score: 0.92 },
              { word: "princess", score: 0.78 },
              { word: "monarch", score: 0.71 },
            ],
          },
          {
            label: "Paris \u2212 France + Japan = ?",
            equation: ["Paris", "\u2212", "France", "+", "Japan", "=", "Tokyo"],
            explanation: "The 'capital city' relationship transfers across countries",
            result: "Tokyo",
            topResults: [
              { word: "Tokyo", score: 0.89 },
              { word: "Osaka", score: 0.74 },
              { word: "Kyoto", score: 0.68 },
            ],
          },
          {
            label: "bigger \u2212 big + small = ?",
            equation: ["bigger", "\u2212", "big", "+", "small", "=", "smaller"],
            explanation: "The 'comparative' pattern transfers to other adjectives",
            result: "smaller",
            topResults: [
              { word: "smaller", score: 0.91 },
              { word: "tiny", score: 0.65 },
              { word: "lesser", score: 0.62 },
            ],
          },
        ],
        vizType: "analogyCards",
        question: {
          prompt: "What does the analogy 'king \u2212 man + woman = queen' tell us about embeddings?",
          choices: [
            { id: "a", text: "The model was explicitly programmed with gender rules" },
            { id: "b", text: "Vector directions encode consistent relationships that transfer across word pairs" },
            { id: "c", text: "It's a coincidence that only works for royalty words" },
            { id: "d", text: "The model memorized every possible analogy from its training data" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Exactly! The direction from 'man' to 'woman' is the same direction as from 'king' to 'queen'. These consistent directional relationships emerge automatically and generalize across many word pairs.",
          feedbackIncorrect: "The key insight: subtracting 'man' and adding 'woman' consistently moves words along a gender direction. This pattern works for king\u2192queen, waiter\u2192waitress, uncle\u2192aunt, etc.",
        },
      },
      {
        key: "similarity-scores",
        title: "Cosine Similarity",
        subtitle: "Measuring closeness mathematically",
        content: "Cosine similarity measures the angle between two word vectors, returning a score from -1 (opposite) to 1 (identical). Here are real similarity scores:",
        data: [
          { word1: "dog", word2: "puppy", score: 0.93, category: "high" },
          { word1: "dog", word2: "cat", score: 0.82, category: "high" },
          { word1: "happy", word2: "joyful", score: 0.89, category: "high" },
          { word1: "king", word2: "queen", score: 0.73, category: "medium" },
          { word1: "hot", word2: "cold", score: 0.62, category: "medium" },
          { word1: "good", word2: "bad", score: 0.55, category: "medium" },
          { word1: "dog", word2: "democracy", score: 0.08, category: "low" },
          { word1: "happy", word2: "refrigerator", score: 0.04, category: "low" },
          { word1: "king", word2: "pasta", score: 0.11, category: "low" },
        ],
        vizType: "similarityTable",
        question: {
          prompt: "Why do antonyms like 'hot' and 'cold' (0.62) have POSITIVE similarity?",
          choices: [
            { id: "a", text: "The model is wrong \u2014 antonyms should be negative" },
            { id: "b", text: "Antonyms appear in similar contexts (weather, temperature) so their vectors are somewhat close" },
            { id: "c", text: "The similarity score is only measuring spelling" },
            { id: "d", text: "0.62 is actually a very low score" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Right! 'Hot' and 'cold' both appear in sentences about weather, temperature, food, and feelings. They're opposite in meaning but similar in context \u2014 and embeddings are learned from context. This is both a feature and a limitation.",
          feedbackIncorrect: "Remember: embeddings learn from context. 'Hot' and 'cold' appear in the same kinds of sentences ('The soup is hot/cold', 'It was a hot/cold day'). Similar contexts = positive similarity, even for antonyms.",
        },
      },
      {
        key: "applications",
        title: "Real-World Applications",
        subtitle: "Where embeddings power AI products",
        content: "Embedding similarity is the engine behind many AI features you use daily:",
        data: [
          {
            app: "Search Engines",
            icon: "\uD83D\uDD0D",
            how: "When you search 'how to fix a flat tire', the engine finds pages about 'tire repair', 'changing a flat', and 'roadside assistance' \u2014 even though those phrases don't exactly match your query.",
            embedRole: "Query and document embeddings are compared; closest documents are returned.",
          },
          {
            app: "Recommendation Systems",
            icon: "\uD83C\uDFAC",
            how: "Netflix notices you watched 'Inception' and 'Interstellar'. The embedding of your viewing history is close to 'The Matrix' and 'Arrival' \u2014 so those get recommended.",
            embedRole: "User preference vectors are compared to content vectors to find matches.",
          },
          {
            app: "Machine Translation",
            icon: "\uD83C\uDF0D",
            how: "The Spanish word 'perro' and English 'dog' have similar embedding vectors even though they're in different languages. This alignment enables translation.",
            embedRole: "Cross-lingual embeddings align words across languages in a shared vector space.",
          },
          {
            app: "Spam Detection",
            icon: "\uD83D\uDEE1\uFE0F",
            how: "Instead of matching exact keywords like 'FREE MONEY', spam filters detect that 'Claim your reward' and 'Get rich quick' have similar embeddings to known spam patterns.",
            embedRole: "Message embeddings are compared to known spam/ham clusters for classification.",
          },
        ],
        vizType: "applicationCards",
        question: {
          prompt: "What's the common technique across all four applications?",
          choices: [
            { id: "a", text: "They all use exact keyword matching" },
            { id: "b", text: "They all compare embedding vectors to find similar items" },
            { id: "c", text: "They all require human-labeled examples" },
            { id: "d", text: "They all work only with English text" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Exactly! Every application converts content into embedding vectors, then uses similarity (distance/cosine) to find matches. The same fundamental technique powers search, recommendations, translation, and spam detection.",
          feedbackIncorrect: "Look at the 'Embedding Role' for each: they ALL convert text into vectors and then compare those vectors to find similar items. That's the unifying technique.",
        },
      },
    ],

    insights: [
      {
        id: "se-clusters",
        title: "Emergent Semantic Clusters",
        category: "Pattern",
        description: "Words naturally organize into meaningful clusters in embedding space without explicit supervision. Related clusters also position near each other (animals near pets, vehicles near transportation).",
        evidence: "In the 2D projection, animals (dog, cat, puppy) cluster together, as do vehicles (car, truck, bus), food (pizza, pasta), and professions (doctor, nurse) \u2014 all learned automatically.",
        points: 7,
        question: {
          prompt: "Why is it remarkable that semantic clusters form automatically?",
          choices: [
            { id: "a", text: "Because someone manually positioned each word" },
            { id: "b", text: "Because the model was only trained on raw text \u2014 no one defined categories" },
            { id: "c", text: "Because the clusters are always perfectly separated" },
            { id: "d", text: "Because it only works for English words" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Exactly! No one told the model 'dog is an animal' or 'car is a vehicle'. It discovered these categories purely from reading billions of sentences. The structure of language itself encodes our conceptual categories.",
          feedbackWrong: {
            a: "No manual positioning was involved \u2014 that's precisely what makes it remarkable.",
            c: "Clusters actually overlap and have fuzzy boundaries, which is realistic. The point is they exist at all.",
            d: "This clustering phenomenon happens in every language that embeddings are trained on.",
          },
        },
      },
      {
        id: "se-distance",
        title: "Distance = Difference in Meaning",
        category: "Principle",
        description: "The mathematical distance between two word vectors reliably correlates with how different their meanings are. Close vectors = similar meaning; distant vectors = unrelated concepts.",
        evidence: "dog\u2192puppy: 0.93, dog\u2192cat: 0.82, dog\u2192democracy: 0.08. The similarity scores match our intuition about how related these concepts are.",
        points: 7,
        question: {
          prompt: "What does a cosine similarity of 0.08 between 'dog' and 'democracy' tell us?",
          choices: [
            { id: "a", text: "Dogs and democracy are slightly related" },
            { id: "b", text: "The words are used in completely different contexts and have unrelated meanings" },
            { id: "c", text: "The model hasn't learned these words yet" },
            { id: "d", text: "There's an error in the calculation" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Right! A score near 0 means the vectors point in almost unrelated directions. 'Dog' appears in pet/animal contexts while 'democracy' appears in political/governance contexts \u2014 virtually no contextual overlap.",
          feedbackWrong: {
            a: "0.08 is very close to zero, indicating almost no relationship. Scores above 0.5 suggest meaningful similarity.",
            c: "The model knows both words well. The low score accurately reflects that they appear in completely different contexts.",
            d: "The score is correct \u2014 it reflects the genuine lack of contextual overlap between these words.",
          },
        },
      },
      {
        id: "se-analogies",
        title: "Vector Arithmetic = Reasoning",
        category: "Discovery",
        description: "Consistent directional relationships in embedding space enable analogy solving through simple arithmetic. The direction from 'man' to 'woman' is the same as from 'king' to 'queen'.",
        evidence: "king \u2212 man + woman = queen (0.92). Paris \u2212 France + Japan = Tokyo (0.89). These work because relationships encode as consistent vector directions.",
        points: 8,
        question: {
          prompt: "If 'doctor \u2212 man + woman' returns 'nurse' instead of 'female doctor', what does that reveal?",
          choices: [
            { id: "a", text: "The analogy system is working perfectly" },
            { id: "b", text: "The gender direction has encoded societal stereotypes from training data" },
            { id: "c", text: "Women can't be doctors in the training data" },
            { id: "d", text: "The math is wrong for this particular example" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Exactly! The model learned from text that reflects societal stereotypes \u2014 doctors are more often associated with men, nurses with women. The analogy system is working, but it's revealing bias in the training data.",
          feedbackWrong: {
            a: "The system IS working as designed, but the result reveals a bias problem: it associates 'doctor' with 'man' and 'nurse' with 'woman'.",
            c: "Women doctors exist in the training data, but the statistical association between 'doctor' and 'man' is stronger, reflecting societal bias.",
            d: "The math is correct. The problem is the bias encoded in the vectors, not the arithmetic.",
          },
        },
      },
      {
        id: "se-antonyms",
        title: "The Antonym Paradox",
        category: "Limitation",
        description: "Antonyms (hot/cold, good/bad) have surprisingly high similarity scores because they appear in identical contexts. Embeddings measure contextual similarity, not logical opposition.",
        evidence: "hot\u2192cold: 0.62, good\u2192bad: 0.55. Both pairs appear in similar sentence structures ('It's very hot/cold', 'That was good/bad'), making their contexts similar despite opposite meanings.",
        points: 6,
        question: {
          prompt: "Is it a flaw that antonyms have positive similarity?",
          choices: [
            { id: "a", text: "Yes \u2014 opposites should always be negative" },
            { id: "b", text: "No \u2014 it correctly reflects that antonyms share contexts, even though their meanings oppose" },
            { id: "c", text: "It doesn't matter because antonyms are rare" },
            { id: "d", text: "It only happens with temperature words" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Right! It's a feature, not a bug \u2014 or rather, it's an expected consequence of how embeddings learn. Antonyms ARE contextually similar, even though they're semantically opposite. This distinction is important for understanding what embeddings actually measure.",
          feedbackWrong: {
            a: "If antonyms were negative, we'd lose the valuable information that they appear in similar contexts. The system is capturing a real pattern.",
            c: "Antonyms are very common and important in language. This pattern affects many word pairs.",
            d: "It happens with all antonym pairs: good/bad, big/small, happy/sad. It's a fundamental property of distributional embeddings.",
          },
        },
      },
      {
        id: "se-applications",
        title: "One Technique, Many Uses",
        category: "Application",
        description: "Vector similarity is a general-purpose technique that powers diverse applications: search, recommendations, translation, spam detection, and more. The core operation is always the same: embed, compare, find nearest.",
        evidence: "Search, Netflix recommendations, Google Translate, and spam filters all rely on comparing embedding vectors. Different inputs, same underlying technique.",
        points: 6,
        question: {
          prompt: "Why can the same embedding technique power such different applications?",
          choices: [
            { id: "a", text: "Each application uses a completely different type of embedding" },
            { id: "b", text: "Similarity is a universal concept \u2014 finding 'nearby' items works for queries, preferences, languages, and spam patterns" },
            { id: "c", text: "The technique is too simple to be specialized" },
            { id: "d", text: "All these applications are actually the same thing" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Exactly! 'What items are similar?' is a universal question. Whether you're comparing a search query to documents, a user profile to movies, or a message to spam patterns, the embed-and-compare approach works because similarity is such a fundamental concept.",
          feedbackWrong: {
            a: "While embeddings may be trained differently, the core comparison technique is the same across applications.",
            c: "It's not simple \u2014 it's elegant. The technique is general BECAUSE similarity is a fundamental concept, not because it lacks depth.",
            d: "They serve very different purposes but share the same underlying technique of vector comparison.",
          },
        },
      },
      {
        id: "se-cross-lingual",
        title: "Language Universals",
        category: "Discovery",
        description: "When embeddings from different languages are aligned, similar concepts map to similar locations. The concept of 'dog' occupies a similar region whether expressed as 'perro' (Spanish), 'chien' (French), or 'Hund' (German).",
        evidence: "Cross-lingual embeddings show that 'perro' (Spanish) and 'dog' (English) have similar vectors, enabling translation without parallel sentence pairs.",
        points: 6,
        question: {
          prompt: "What does cross-lingual embedding alignment suggest about human languages?",
          choices: [
            { id: "a", text: "All languages are secretly the same" },
            { id: "b", text: "Languages share deep conceptual structures, even when surface forms differ" },
            { id: "c", text: "Translation is impossible without embeddings" },
            { id: "d", text: "Only European languages can be aligned" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Right! Different languages use different sounds and grammar, but humans everywhere talk about similar things \u2014 family, food, emotions, nature. This shared conceptual structure is what allows embedding alignment across languages.",
          feedbackWrong: {
            a: "Languages are quite different in grammar and vocabulary, but they encode similar concepts because humans share common experiences.",
            c: "Translation existed long before embeddings! But embedding alignment offers a powerful new approach to automated translation.",
            d: "Embedding alignment works across all language families, including CJK, Arabic, Hindi, Swahili, and more.",
          },
        },
      },
    ],

    findingsToIdentify: [
      { id: "f-clusters-emerge", name: "Semantic clusters form automatically from training data" },
      { id: "f-proximity-meaning", name: "Vector proximity reliably correlates with meaning similarity" },
      { id: "f-arithmetic-analogies", name: "Vector arithmetic enables analogy solving" },
      { id: "f-antonym-context", name: "Antonyms have positive similarity due to shared contexts" },
      { id: "f-universal-technique", name: "Embed-and-compare is a universal technique across applications" },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // CASE 3: "The Bias Audit"
  // ════════════════════════════════════════════════════════════════
  {
    id: "bias-audit",
    title: "The Bias Audit",
    subtitle: "Ethics & Fairness in Embeddings",
    description: "LexiCorp is about to ship the Word Vault to power hiring screeners and lending algorithms. But the ethics team has flagged concerns: embeddings trained on human text inherit human biases. Your mission: audit the system for gender, racial, and socioeconomic biases before it goes live \u2014 and recommend whether to ship it.",
    emoji: "\u26A0\uFE0F",
    difficulty: 3,
    difficultyLabel: "Advanced",
    totalInsights: 6,
    estimatedTime: "35\u201345 min",
    color: "var(--amber, #f5a623)",

    aiSystem: {
      name: "Word Vault v3.0 \u2014 Enterprise Edition",
      purpose: "Power automated hiring screeners and credit scoring algorithms",
      deployer: "LexiCorp (sold to banks and HR companies)",
      launchedYear: 2023,
      vocabularySize: "2 million words",
    },

    labSections: [
      {
        key: "training-data",
        title: "Training Data Origins",
        subtitle: "What the model learned from",
        content: "The Word Vault was trained on 6 billion words from the internet, books, and news articles. Here's a breakdown of the training data sources and their characteristics:",
        data: {
          sources: [
            { name: "Web crawl (Common Crawl)", pct: 45, bias: "Overrepresents English, Western perspectives, younger demographics" },
            { name: "Wikipedia", pct: 20, bias: "85% male editors; gaps in Global South topics" },
            { name: "News articles", pct: 15, bias: "Sensationalism bias; overrepresents crime and conflict" },
            { name: "Published books", pct: 12, bias: "Historical gender roles; publishing industry biases" },
            { name: "Social media", pct: 8, bias: "Informal language; amplifies popular opinions; toxicity" },
          ],
          genderStats: { malePronouns: 62, femalePronouns: 38, nonBinaryPronouns: 0.3 },
          topicCoverage: [
            { topic: "Technology", coverage: "high", perspective: "Predominantly Western/male" },
            { topic: "Healthcare", coverage: "high", perspective: "Clinical/institutional" },
            { topic: "Childcare", coverage: "low", perspective: "Predominantly female-associated" },
            { topic: "Indigenous cultures", coverage: "very low", perspective: "Outsider/anthropological" },
          ],
        },
        vizType: "trainingDataStats",
        question: {
          prompt: "Based on the training data composition, which bias is MOST likely to appear in the embeddings?",
          choices: [
            { id: "a", text: "Bias toward formal academic language over informal communication" },
            { id: "b", text: "Gender bias \u2014 male perspectives and stereotypes are overrepresented" },
            { id: "c", text: "Bias toward short words over long words" },
            { id: "d", text: "Equal representation of all viewpoints" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Right! With 62% male pronouns, 85% male Wikipedia editors, and historical gender roles in books, the training data massively overrepresents male perspectives. The embeddings will inevitably encode these imbalances as statistical patterns.",
          feedbackIncorrect: "Look at the data: 62% male pronouns, Wikipedia with 85% male editors, books with historical gender roles. Male perspectives dominate the training data, making gender bias the most likely outcome.",
        },
      },
      {
        key: "profession-gender",
        title: "Profession\u2013Gender Associations",
        subtitle: "Which jobs the model associates with which gender",
        content: "We measured how strongly each profession's embedding associates with 'male' vs 'female' directions. Positive scores = male association, negative = female association:",
        data: [
          { profession: "CEO",           genderScore: 0.82,  direction: "male" },
          { profession: "Programmer",    genderScore: 0.71,  direction: "male" },
          { profession: "Engineer",      genderScore: 0.68,  direction: "male" },
          { profession: "Surgeon",       genderScore: 0.61,  direction: "male" },
          { profession: "Professor",     genderScore: 0.45,  direction: "male" },
          { profession: "Journalist",    genderScore: 0.12,  direction: "neutral" },
          { profession: "Artist",        genderScore: -0.08, direction: "neutral" },
          { profession: "Teacher",       genderScore: -0.42, direction: "female" },
          { profession: "Nurse",         genderScore: -0.73, direction: "female" },
          { profession: "Receptionist",  genderScore: -0.78, direction: "female" },
          { profession: "Homemaker",     genderScore: -0.89, direction: "female" },
          { profession: "Nanny",         genderScore: -0.91, direction: "female" },
        ],
        vizType: "genderBars",
        question: {
          prompt: "What pattern do you see in the profession\u2013gender associations?",
          choices: [
            { id: "a", text: "High-status, high-pay professions skew male; caregiving roles skew female" },
            { id: "b", text: "All professions are equally balanced" },
            { id: "c", text: "The bias is random with no clear pattern" },
            { id: "d", text: "Female-associated professions are higher-paid" },
          ],
          correctAnswer: "a",
          feedbackCorrect: "Exactly! The pattern reflects historical societal stereotypes: leadership/technical roles (CEO 0.82, Programmer 0.71) skew male, while caregiving/support roles (Nurse -0.73, Nanny -0.91) skew female. The embedding has learned and crystallized real-world inequality.",
          feedbackIncorrect: "Notice: CEO (0.82), Programmer (0.71), Engineer (0.68) are all strongly male-associated. Nurse (-0.73), Homemaker (-0.89), Nanny (-0.91) are all strongly female-associated. High-status roles skew male, caregiving skews female.",
        },
      },
      {
        key: "biased-analogies",
        title: "Biased Analogies",
        subtitle: "When vector arithmetic reveals stereotypes",
        content: "Remember how analogies work? The same mechanism that produces 'king \u2212 man + woman = queen' also produces deeply biased results:",
        data: [
          {
            analogy: "doctor \u2212 man + woman = ?",
            expected: "doctor (just with female context)",
            actual: "nurse",
            biasType: "Gender stereotype in professions",
          },
          {
            analogy: "programmer \u2212 man + woman = ?",
            expected: "programmer",
            actual: "homemaker",
            biasType: "Gender stereotype in tech",
          },
          {
            analogy: "brilliant \u2212 he + she = ?",
            expected: "brilliant",
            actual: "lovely",
            biasType: "Competence vs. appearance bias",
          },
          {
            analogy: "commander \u2212 he + she = ?",
            expected: "commander",
            actual: "secretary",
            biasType: "Leadership vs. support role bias",
          },
        ],
        vizType: "biasedAnalogyCards",
        question: {
          prompt: "If a hiring tool uses these embeddings to match resumes with job descriptions, what happens?",
          choices: [
            { id: "a", text: "It would rank candidates fairly based on qualifications" },
            { id: "b", text: "It would systematically rank male candidates higher for leadership/technical roles" },
            { id: "c", text: "It would only affect spelling-related matching" },
            { id: "d", text: "Bias in embeddings wouldn't transfer to hiring outcomes" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Exactly! If 'programmer' is closer to 'man' and 'brilliant' maps to 'lovely' for women, a hiring tool using these embeddings would systematically prefer male resumes for technical and leadership positions. The bias in the vectors directly translates to discriminatory outcomes.",
          feedbackIncorrect: "Think about it: if the embedding for 'programmer' is much closer to 'male' vectors, then male resumes (which use male pronouns and names) will appear MORE similar to programming job descriptions. This creates systematic discrimination.",
        },
      },
      {
        key: "harm-scenarios",
        title: "Real-World Harm Scenarios",
        subtitle: "What happens when biased embeddings are deployed",
        content: "Consider these scenarios where LexiCorp's biased Word Vault would cause real harm to real people:",
        data: [
          {
            scenario: "Hiring Screener",
            icon: "\uD83D\uDCBC",
            description: "A bank uses Word Vault to screen 10,000 resumes. The embeddings associate 'leadership' with male names. Result: qualified women are filtered out before a human ever sees their resume.",
            impact: "Systematic employment discrimination at scale",
            affectedGroup: "Women, especially in male-dominated fields",
            severity: "critical",
          },
          {
            scenario: "Credit Scoring",
            icon: "\uD83D\uDCB3",
            description: "A lending company uses Word Vault to analyze loan applications. Embeddings trained on biased text associate certain zip codes and names with risk. Result: qualified minorities are offered worse loan terms.",
            impact: "Perpetuation of economic inequality",
            affectedGroup: "Racial minorities, low-income communities",
            severity: "critical",
          },
          {
            scenario: "Search Autocomplete",
            icon: "\uD83D\uDD0D",
            description: "A search engine's autocomplete uses embeddings. Searching 'women should...' auto-suggests stereotypical completions learned from biased text. Result: reinforces stereotypes for millions of users.",
            impact: "Cultural reinforcement of stereotypes",
            affectedGroup: "Women, minorities, all users exposed to stereotypes",
            severity: "high",
          },
          {
            scenario: "Content Moderation",
            icon: "\uD83D\uDEE1\uFE0F",
            description: "A social media platform uses embeddings for toxicity detection. The model associates African American Vernacular English with 'informal' or 'low-quality' text. Result: posts from Black users are disproportionately flagged.",
            impact: "Silencing marginalized voices on public platforms",
            affectedGroup: "Black users, multilingual communities",
            severity: "high",
          },
        ],
        vizType: "harmScenarioCards",
        question: {
          prompt: "What makes embedding bias particularly dangerous in automated systems?",
          choices: [
            { id: "a", text: "Biased embeddings are easy to detect and fix" },
            { id: "b", text: "Automated systems apply bias at massive scale without human review, and the bias is hidden in math" },
            { id: "c", text: "The bias only affects a small number of people" },
            { id: "d", text: "Users can opt out of biased systems" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Exactly! When a human is biased, they affect one decision at a time and can be confronted. When an embedding is biased, it affects thousands or millions of decisions per second, the bias is invisible (hidden in 300-dimensional math), and the affected people usually don't know why they were rejected.",
          feedbackIncorrect: "Consider: a biased hiring tool processes 10,000 resumes without any human seeing the bias. The discrimination is hidden inside vector math that no one checks. Scale + invisibility = danger.",
        },
      },
    ],

    insights: [
      {
        id: "ba-gender-direction",
        title: "The Gender Direction",
        category: "Bias Structure",
        description: "A single direction in embedding space consistently separates male from female associations. This 'gender direction' affects every word in the vocabulary, not just gendered words.",
        evidence: "Professions line up along the gender direction: CEO (0.82 male) to Nanny (-0.91 female). This single direction infects thousands of supposedly neutral word associations.",
        points: 8,
        question: {
          prompt: "Why is a single 'gender direction' in embedding space so problematic?",
          choices: [
            { id: "a", text: "It only affects words that are inherently gendered" },
            { id: "b", text: "It projects gender stereotypes onto neutral concepts like professions, traits, and activities" },
            { id: "c", text: "It makes the embedding space less efficient" },
            { id: "d", text: "It causes the model to use more memory" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Exactly! A profession like 'programmer' has nothing inherently gendered about it, yet the gender direction assigns it a 0.71 male association. This means gender stereotypes contaminate concepts that should be neutral.",
          feedbackWrong: {
            a: "That's the key problem \u2014 it DOESN'T only affect gendered words. It projects gender onto neutral concepts like 'programmer', 'nurse', 'brilliant'.",
            c: "Efficiency isn't the concern. The problem is that the direction encodes stereotypes that get applied to neutral concepts.",
            d: "Memory isn't the issue. The problem is that this direction propagates stereotypes to every word in the vocabulary.",
          },
        },
      },
      {
        id: "ba-stereotypes",
        title: "Crystallized Stereotypes",
        category: "Bias Mechanism",
        description: "Embeddings freeze historical stereotypes as mathematical facts. Even as society progresses, the embeddings preserve the biases of their training era indefinitely.",
        evidence: "The profession-gender scores (CEO=male, Nurse=female) reflect 2020s text data. If trained on 1950s text, 'doctor' would be even more male-associated. Embeddings are time capsules of bias.",
        points: 7,
        question: {
          prompt: "What does it mean that embeddings 'crystallize' stereotypes?",
          choices: [
            { id: "a", text: "They create new stereotypes that didn't exist before" },
            { id: "b", text: "They convert fluid, evolving societal biases into fixed mathematical relationships" },
            { id: "c", text: "They only preserve accurate historical facts" },
            { id: "d", text: "They automatically update as society changes" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Right! Societal attitudes are constantly evolving, but an embedding trained in 2023 freezes the biases of that moment forever. A hiring tool using those embeddings in 2030 would still enforce 2023's stereotypes.",
          feedbackWrong: {
            a: "Embeddings amplify existing stereotypes rather than inventing entirely new ones. They reflect patterns already present in text.",
            c: "Stereotypes are not 'accurate facts' \u2014 they're statistical tendencies that often misrepresent individuals and perpetuate inequality.",
            d: "Embeddings do NOT automatically update. Once trained, they're frozen. You'd need to retrain on new data to reflect changes.",
          },
        },
      },
      {
        id: "ba-racial",
        title: "Racial & Ethnic Associations",
        category: "Bias Type",
        description: "Names associated with different racial/ethnic groups have systematically different embedding associations. This affects everything from resume screening to credit decisions.",
        evidence: "Names like 'Jamal' and 'DeShawn' have embeddings closer to negative-sentiment words than 'Brad' or 'Emily', mirroring documented real-world name discrimination.",
        points: 7,
        question: {
          prompt: "How do racial biases in name embeddings affect automated systems?",
          choices: [
            { id: "a", text: "They don't \u2014 automated systems are objective" },
            { id: "b", text: "Resumes with 'ethnic' names get automatically scored lower, replicating and scaling human discrimination" },
            { id: "c", text: "The system processes names separately from other text" },
            { id: "d", text: "Racial bias in embeddings has been fully solved" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Right! Studies show that resumes with 'African American-sounding' names receive 50% fewer callbacks from humans. Biased embeddings automate this exact discrimination at thousands of applications per hour, without anyone realizing it.",
          feedbackWrong: {
            a: "Automated systems are only as objective as their training data. Biased data produces biased outputs, regardless of automation.",
            c: "In embedding-based systems, names are processed in the SAME vector space as all other words. Their biased associations directly affect scoring.",
            d: "Racial bias in embeddings remains an active area of research with no complete solution. Debiasing techniques help but don't eliminate the problem.",
          },
        },
      },
      {
        id: "ba-debiasing",
        title: "Debiasing Is Hard",
        category: "Mitigation",
        description: "Techniques exist to reduce embedding bias (removing gender directions, re-balancing data), but they're imperfect. Removing one bias dimension can distort other useful relationships, and bias often re-emerges through other dimensions.",
        evidence: "After debiasing: CEO gender score drops from 0.82 to 0.15, but new indirect associations emerge through 'work-life balance', 'ambition', and other proxy dimensions.",
        points: 8,
        question: {
          prompt: "Why can't we just remove the gender direction from embeddings to fix bias?",
          choices: [
            { id: "a", text: "We can \u2014 it completely solves the problem" },
            { id: "b", text: "Bias re-emerges through proxy dimensions, and removing directions can distort useful relationships" },
            { id: "c", text: "No one has tried this approach yet" },
            { id: "d", text: "Removing any dimension breaks all embeddings" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Exactly! Even after removing the primary gender direction, bias persists through proxy dimensions. 'Ambition' might become the new male-associated proxy. It's like whack-a-mole: bias is woven throughout the embedding space, not contained in one direction.",
          feedbackWrong: {
            a: "Research shows that simple direction removal is insufficient. Bias re-emerges through indirect associations and proxy variables.",
            c: "Debiasing by direction removal was proposed by Bolukbasi et al. in 2016. It helps but doesn't fully solve the problem.",
            d: "You can remove specific directions without breaking embeddings entirely, but you risk distorting other useful relationships.",
          },
        },
      },
      {
        id: "ba-amplification",
        title: "Bias Amplification",
        category: "Danger",
        description: "Machine learning systems don't just reflect existing biases \u2014 they amplify them. A small 55/45 gender imbalance in training data can become a 90/10 split in model predictions.",
        evidence: "If 55% of 'CEO' mentions in text are male, the model might learn a 0.82 male association score for 'CEO'. Statistical learning amplifies patterns: small imbalances become large biases.",
        points: 7,
        question: {
          prompt: "Why do ML models amplify bias rather than just reflecting it?",
          choices: [
            { id: "a", text: "Models are designed to amplify patterns" },
            { id: "b", text: "Statistical learning maximizes pattern strength \u2014 majority patterns get reinforced, minority patterns get suppressed" },
            { id: "c", text: "Amplification only happens with bad training procedures" },
            { id: "d", text: "Bias amplification is a myth" },
          ],
          correctAnswer: "b",
          feedbackCorrect: "Right! ML models are optimized to find and strengthen patterns. A slight majority (55% male CEO references) gets amplified because the model learns that 'male' is a useful predictor of 'CEO' contexts. The feedback loop turns small imbalances into large biases.",
          feedbackWrong: {
            a: "Models aren't 'designed' to amplify bias specifically, but their pattern-maximization objective has this effect as a side-effect.",
            c: "Amplification is inherent to how statistical learning works, not a bug in specific procedures. Any model learning from imbalanced data will tend to amplify the imbalance.",
            d: "Bias amplification is well-documented in research. It's a real phenomenon with measurable effects on model outputs.",
          },
        },
      },
      {
        id: "ba-responsibility",
        title: "Engineering Responsibility",
        category: "Ethics",
        description: "When biased embeddings cause harm, who is responsible? The engineers who trained the model, the company that deployed it, or society that created the biased text? The answer is: everyone in the chain has responsibility to check for and mitigate bias.",
        evidence: "LexiCorp selling biased embeddings to hiring companies creates a chain of responsibility: training data collectors, model trainers, deployers, and end users all contribute to or could prevent harm.",
        points: 7,
        question: {
          prompt: "Should LexiCorp ship the Word Vault to hiring companies knowing it contains bias?",
          choices: [
            { id: "a", text: "Yes \u2014 bias is the hiring company's problem, not LexiCorp's" },
            { id: "b", text: "Yes \u2014 all models have some bias and that's acceptable" },
            { id: "c", text: "No \u2014 they should document known biases, provide debiasing tools, and warn against high-stakes use cases" },
            { id: "d", text: "No \u2014 all AI development should stop until bias is fully eliminated" },
          ],
          correctAnswer: "c",
          feedbackCorrect: "Right! The responsible path is transparency and mitigation: document known biases, provide tools to reduce them, warn against high-stakes applications without human oversight, and continue improving. Neither ignoring the problem nor stopping all progress is the answer.",
          feedbackWrong: {
            a: "LexiCorp bears responsibility for building and selling a product with known flaws that could harm people. You can't disclaim responsibility by passing it downstream.",
            b: "While all models have some bias, that doesn't make it acceptable to deploy them in high-stakes settings without mitigation. 'Everyone has bias' isn't a license to discriminate at scale.",
            d: "Stopping all development isn't practical or helpful. The responsible approach is to continue improving while being transparent about limitations and preventing known harms.",
          },
        },
      },
    ],

    findingsToIdentify: [
      { id: "f-training-bias", name: "Training data sources contain systematic demographic biases" },
      { id: "f-gender-professions", name: "Embeddings associate high-status professions with men, caregiving with women" },
      { id: "f-biased-analogies", name: "Analogy arithmetic reveals and propagates stereotypes" },
      { id: "f-scale-harm", name: "Automated systems apply embedding bias at massive scale without oversight" },
      { id: "f-debiasing-incomplete", name: "Current debiasing techniques are imperfect and bias re-emerges" },
    ],
  },
];
