module.exports = {
  printableFilename: null,
  blocks: [],
  replacesFinalSortingItems: true,
  newSortingTitle: "Whose Brushstroke?",
  newSortingInstructions: "Each tile is a real image. Swipe it to the side you think is true. Some were made by a human artist. Some were generated by AI. Trust your eye — then we'll reveal.",
  newSortingLeftLabel: "Human artist",
  newSortingRightLabel: "AI-generated",
  newSortingItems: [
    { text: "Watercolor cityscape at dusk", correct: "left",  imageSlug: "art-gallery-01-human-watercolor-cityscape" },
    { text: "Oil portrait of elderly farmer", correct: "left",  imageSlug: "art-gallery-02-human-oil-portrait" },
    { text: "Sci-fi landscape, three suns", correct: "right", imageSlug: "art-gallery-03-ai-scifi-landscape" },
    { text: "Photo of a bowl of fruit", correct: "left",  imageSlug: "art-gallery-04-human-still-life-photo" },
    { text: "Dragon in a crystal forest", correct: "right", imageSlug: "art-gallery-05-ai-dragon-forest" },
    { text: "Charcoal sketch of running horses", correct: "left",  imageSlug: "art-gallery-06-human-charcoal-horses" },
    { text: "Astronaut surfing a wave of stars", correct: "right", imageSlug: "art-gallery-07-ai-astronaut-surf" },
    { text: "Street photography, rainy crosswalk", correct: "left",  imageSlug: "art-gallery-08-human-street-photo" },
  ],
};
