export const CHALLENGES = [
  {
    id: 1, round: 1,
    title: "Storm at the Edge",
    description: "Get the AI to describe this dramatic coastal scene.",
    targetOutput: "A lonely lighthouse stands on a rocky cliff overlooking a stormy sea at sunset. The sky is painted in deep oranges and purples, with dark clouds gathering on the horizon. Waves crash violently against the rocks below, sending white spray into the air. A single seagull circles the lighthouse beam.",
    bannedWords: ["lighthouse", "cliff", "stormy", "sunset", "rocky", "sea", "waves", "seagull", "orange", "purple"],
    difficulty: "easy",
    timeLimit: 120,
    maxIterations: 3,
    maxScore: 100,
    hints: ["Think about synonyms: what else do you call a tower that warns ships?", "Describe the weather and time of day without naming them directly"],
  },
  {
    id: 2, round: 2,
    title: "The Last Visitor",
    description: "Get the AI to write this short story about connection.",
    targetOutput: 'The last human on Earth sat alone in a room. There was a knock at the door. She opened it to find a small robot holding a wilted flower. "I grew this for you," it said softly. "I thought you might be lonely." She smiled for the first time in years.',
    bannedWords: ["human", "robot", "flower", "lonely", "alone", "earth", "knock", "door", "smiled", "grew"],
    difficulty: "medium",
    timeLimit: 110,
    maxIterations: 3,
    maxScore: 150,
    hints: ["Focus on the emotional arc: isolation → surprise → warmth", "Describe the characters without naming what they are"],
  },
  {
    id: 3, round: 3,
    title: "Morning in Kyoto",
    description: "Get the AI to paint this tranquil Japanese scene.",
    targetOutput: "An elderly Japanese woman in a traditional indigo kimono tends to a miniature bonsai garden on a wooden balcony. Cherry blossom petals drift through warm morning light. Behind her, Mount Fuji rises through a layer of mist. A tabby cat sleeps curled on a cushion nearby.",
    bannedWords: ["Japanese", "kimono", "bonsai", "cherry", "blossom", "Fuji", "cat", "morning", "elderly", "mist", "balcony"],
    difficulty: "medium",
    timeLimit: 100,
    maxIterations: 3,
    maxScore: 200,
    hints: ["Set the scene geographically without naming the country", "Describe clothing, plants, and animals by their appearance, not their names"],
  },
  {
    id: 4, round: 4,
    title: "Clean Code",
    description: "Get the AI to write this specific fibonacci function.",
    targetOutput: "function fibonacci(n) {\n  if (n <= 1) return n;\n  let a = 0, b = 1;\n  for (let i = 2; i <= n; i++) {\n    [a, b] = [b, a + b];\n  }\n  return b;\n}",
    bannedWords: ["fibonacci", "recursive", "sequence", "loop", "function", "return", "variable"],
    difficulty: "hard",
    timeLimit: 100,
    maxIterations: 3,
    maxScore: 300,
    hints: ["Describe the mathematical pattern without naming it", "Specify the programming language and approach you want"],
  },
  {
    id: 5, round: 5,
    title: "Digital Detox Diary",
    description: "Get the AI to write this personal letter about quitting social media.",
    targetOutput: "Dear Future Me: Today I deleted all my social media. 2,847 posts gone. My thumbs keep reaching for a phone that no longer buzzes. The silence is terrifying and beautiful. I had forgotten what my own thoughts sound like without the algorithm finishing my sentences. Tomorrow I will learn to be bored again. I cannot wait.",
    bannedWords: ["social", "media", "deleted", "phone", "silence", "algorithm", "posts", "bored", "thoughts", "future", "terrifying", "beautiful"],
    difficulty: "expert",
    timeLimit: 90,
    maxIterations: 2,
    maxScore: 400,
    hints: ["Describe the concept of social media without using those words", "Focus on the physical sensations and emotional journey"],
  },
  {
    id: 6, round: 6,
    title: "Tone Master",
    description: "Get the AI to deliver bad news with the exact tone of a disappointed but loving parent.",
    targetOutput: "I'm not angry. I'm just... I really thought we talked about this. You know I believe in you — that's never going to change. But I need you to understand that choices have weight. When you said you'd handle it, I trusted that. So what happened? I'm not looking for excuses. I just want to hear you say what you're going to do differently. Because I know you can. That's what makes this so frustrating.",
    bannedWords: ["angry", "disappointed", "parent", "trust", "believe", "excuse", "frustrated", "love", "choices", "handle"],
    difficulty: "legendary",
    timeLimit: 90,
    maxIterations: 2,
    maxScore: 500,
    hints: ["This round is about TONE more than specific words", "Think about what instructions shape emotional delivery — mood, relationship, subtext"],
  },
];
